# Generated by Django 2.0.3 on 2018-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180401_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bodytext',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='categories.Category', verbose_name='Категории'),
        ),
    ]
